# -*- coding: utf-8 -*-
"""the estimater 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibcWv_CO__e2hNYSTBGmvNea1GWT7Hcv
"""

from google.colab import files
uploaded = files.upload()

!pip install streamlit pyngrok --quiet

!pkill streamlit

ngrok.set_auth_token("2z4lIJbUZlShGiWAFguNzXGeBjV_cvZhUjaYMoghakaw8gCZ")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# import numpy as np
# 
# model = joblib.load("traffic_volume_model.pkl")
# 
# st.title("Traffic Volume Estimator")
# 
# temp = st.number_input("Temperature (°C):")
# rain = st.number_input("Rain (mm):")
# clouds = st.slider("Cloud coverage (%):", 0, 100, 50)
# 
# if st.button("Predict"):
#     features = np.array([[temp, rain, clouds]])
#     prediction = model.predict(features)[0]
#     st.success(f"Estimated Traffic Volume: {int(prediction)} vehicles")

from google.colab import files
files.upload()

import os
print(os.listdir())

import os
from pyngrok import ngrok

# Set your ngrok authtoken
ngrok.set_auth_token("2z4lIJbUZlShGiWAFguNzXGeBjV_cvZhUjaYMoghakaw8gCZ")

# Kill any existing Streamlit processes
!pkill streamlit

# Run Streamlit in the background
os.system("streamlit run app.py &")

# Start tunnel
public_url = ngrok.connect(addr="8501")
print("✅ Your Streamlit app is live at:", public_url)